name: birmbenawa
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intro_slider: ^4.2.0
  introduction_screen: ^3.0.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  google_fonts: ^4.0.3
  dropdown_button2: ^2.0.0
  auto_size_text_field: ^2.1.0
  animated_toggle_switch: ^0.6.2
  auto_size_text: ^3.0.0
  adaptive_action_sheet: ^2.0.2
  get: ^4.6.5
  tip_dialog: ^4.0.0
  custom_bottom_sheet: ^1.1.2
  flutter_slidable: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  roundcheckbox: ^2.0.5
  timezone: ^0.9.1
  rxdart: ^0.27.5
  bottom_sheet: ^3.1.1
  awesome_notifications: ^0.7.4+1
  calender_picker: ^2.0.1
  day_picker: ^2.1.1
  syncfusion_flutter_datepicker: ^21.1.37
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#ffffff" #white color
  image: assets/logoNoBackground.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logoNoBackground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: RaberR
      fonts: 
        - asset: fonts/RabarRegular.ttf
    - family: RaberB
      fonts: 
        - asset: fonts/RabarBold.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/logo.png
    - assets/images/slider/REMINDER.png
    - assets/images/slider/SHOP.png
    - assets/images/slider/Weekly.png
    - assets/images/AriAhmedPic.png
    - assets/icons/favicon.ico
    - assets/images/slider/Buy.png
    - assets/images/slider/Debt_Analyses.png
    - assets/images/slider/List_Of_Task.png
    - assets/images/slider/SignIn.png
    - assets/images/slider/Developing.png
    - assets/images/slider/SignUp.png
    - assets/logoNoBackground.png
    - assets/images/process/confirmed.png
    - assets/images/process/empty_screen.png
    - assets/images/process/error.png
    - assets/images/edit_screen.png
    - assets/images/banner.jpg
    - assets/images/arrow.png
    - assets/notification_reminder_image.jpg
    - assets/Rwanga_logo.png