name: birmbenawa
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intro_slider: ^3.0.9
  introduction_screen: ^3.0.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  flutter_iconpicker: ^3.1.4+1
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  hidden_drawer_menu: ^3.0.1
  android_alarm_manager_plus: ^2.0.6+1
  google_fonts: ^3.0.1
  dropdown_button2: ^1.7.2
  auto_size_text_field: ^2.1.0
  animated_toggle_switch: ^0.5.2
  flutter_material_color_picker: ^1.1.0+2
  auto_size_text: ^3.0.0
  adaptive_action_sheet: ^2.0.2
  get: ^4.6.5
  tip_dialog: ^4.0.0
  msh_checkbox: ^1.1.1
  custom_bottom_sheet: ^1.1.2
  flutter_slidable: ^2.0.0
  internet_connection_checker: ^0.0.1+4
  overlay_support: ^2.0.1
  flutter_local_notifications: ^9.8.0+1
  rxdart: ^0.27.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0


flutter_icons:
  image_path: assets/images/slider/logo.png
  android: true
  ios: true


flutter:
  uses-material-design: true
  fonts:
    - family: KurdBold
      fonts: 
        - asset: fonts/K24KurdishBold-Bold.ttf
    - family: KurdLight
      fonts: 
        - asset: fonts/K24KurdishLight-Light.ttf
    - family: PeshangBold
      fonts: 
        - asset: fonts/peshangBold.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/slider/logo.png
    - assets/images/slider/REMINDER.png
    - assets/images/slider/SHOP.png
    - assets/images/slider/Weekly.png
    - assets/images/AriAhmedPic.png
    - assets/icons/favicon.ico
    - assets/images/Buy.png
    - assets/images/Debt_Analyses.png
    - assets/images/List_Of_Task.png
    - assets/images/SignIn.png
    - assets/images/Developing.png
    - assets/images/slider/SignUp.png
    - assets/images/slider/logoNoBackground.png
    - assets/images/process/confirmed.png
    - assets/images/process/empty_screen.png
    - assets/images/process/error.png
    - assets/images/edit_screen.png
    - assets/images/banner.jpg
    - assets/images/arrow.png
