name: birmbenawa
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intro_slider: ^3.0.9
  introduction_screen: ^3.0.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  flutter_iconpicker: ^3.1.4+1

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  image_path: assets/images/slider/logo.png
  android: true
  ios: true


flutter:
  uses-material-design: true
  fonts:
    - family: KurdBold
      fonts: 
        - asset: fonts/K24KurdishBold-Bold.ttf
    - family: KurdLight
      fonts: 
        - asset: fonts/K24KurdishLight-Light.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/slider/logo.png
    - assets/images/slider/bgslides.jpg
    - assets/images/slider/REMINDER.png
    - assets/images/slider/SHOP.png
    - assets/images/slider/Weekly.png
    - assets/images/AriAhmedPic.png
    - assets/icons/favicon.ico
