name: birmbenawa
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intro_slider: ^3.0.9
  introduction_screen: ^3.0.1
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  flutter_iconpicker: ^3.1.4+1
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  hidden_drawer_menu: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0


flutter_icons:
  image_path: assets/images/slider/logo.png
  android: true
  ios: true


flutter:
  uses-material-design: true
  fonts:
    - family: KurdBold
      fonts: 
        - asset: fonts/K24KurdishBold-Bold.ttf
    - family: KurdLight
      fonts: 
        - asset: fonts/K24KurdishLight-Light.ttf
    - family: PeshangBold
      fonts: 
        - asset: fonts/peshangBold.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/slider/logo.png
    - assets/images/slider/REMINDER.png
    - assets/images/slider/SHOP.png
    - assets/images/slider/Weekly.png
    - assets/images/AriAhmedPic.png
    - assets/icons/favicon.ico
    - assets/images/Buy.png
    - assets/images/Dabt_Analyser.png
    - assets/images/List_Of_Task.png
    - assets/images/SignIn.png
    - assets/images/Developing.png
    - assets/images/slider/SignUp.png
    - assets/images/slider/logoNoBackground.png
