// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDwLVSBTBszopTNykWeoVf3mBkZJ1u2I',
    appId: '1:467745792140:web:46fc5bb5f3ff3c4c9edba9',
    messagingSenderId: '467745792140',
    projectId: 'birmbenawa',
    authDomain: 'birmbenawa.firebaseapp.com',
    storageBucket: 'birmbenawa.appspot.com',
    measurementId: 'G-4H6NX8QTP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQU3M3nt1hCQp-6xQNIz9We5NVhZdCazk',
    appId: '1:467745792140:android:00c6c0da430a1d899edba9',
    messagingSenderId: '467745792140',
    projectId: 'birmbenawa',
    storageBucket: 'birmbenawa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbiNmkWilMVZFu2yJOcvwC9jKsgG9W2W4',
    appId: '1:467745792140:ios:0d7482d2671df49f9edba9',
    messagingSenderId: '467745792140',
    projectId: 'birmbenawa',
    storageBucket: 'birmbenawa.appspot.com',
    iosClientId: '467745792140-mchmgogfa8eqfa3kdh8kn2a44n47gb3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.birmbenawa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbiNmkWilMVZFu2yJOcvwC9jKsgG9W2W4',
    appId: '1:467745792140:ios:0d7482d2671df49f9edba9',
    messagingSenderId: '467745792140',
    projectId: 'birmbenawa',
    storageBucket: 'birmbenawa.appspot.com',
    iosClientId: '467745792140-mchmgogfa8eqfa3kdh8kn2a44n47gb3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.birmbenawa',
  );
}
